#!/bin/bash

#for n in ram sham mohan
#do
#echo "Welcome $n"
#done

#for n in `cat /etc/passwd`
#do
#echo $n
#done

##### Not Working ######
#for n in {1..10}
#do
#echo "The value is $n"
#done
#
###
#
#for (( a = 1,b = 10;$a <= 10;a++,b-- ))
#do
#c = $[ $a + $b ]
#echo "$a + $b = $c"
#done
#######################

for ((a = 1 ; $a <= 10 ; a++))
do
	if[ $a -eq 5 ]
	then
	continue
	fi
echo "New no. is $a"
done

for ((a=1;$a<=10;a++))
do
echo "Start ======== $a"
	for ((b=1;$b<=10;b++))
	do
	if[ $b -eq 5 ]
	then
	continue
	fi
	echo "Number is $b"
	done
echo "End ========== $b"
done
