#!/bin/bash
echo "RIGHTANGLE TRIANGLE"
#RIGHT ANGLE TRIANGLE
CO=20
for(( A=1;$A<=$CO;A++ ))
do
	for(( B=1;$B<=$A;B++ ))
	do
	echo -n "*"
	done
echo
done

echo
echo "TRIANGLE"
#RIGHT ANGLE TRIANGLE double
CO=20
for(( A=1;$A<=$CO;A++ ))
do
	for(( B=1;$B<=$A;B++ ))
	do
	echo -n "*"
	done
echo
done
for(( A=$CO-1;$A>=1;A-- ))
do
	for(( B=$A;$B>=1;B-- ))
	do
	echo -n "*"
	done
echo
done

echo
echo "REVERSE RIGHTANGLE TRIANGLE"
#REVERSE RIGHT ANGLE TRIANGLE
CO=20
for(( A=1;$A<=$CO;A++ ))
do
	for(( C=$CO;$C>=$A;C-- ))
	do
	echo -n "*"
	done
echo
done

echo
echo "PYRAMID"
#TRIANGLE
COD=20
CO=20
for(( A=1;$A<=$CO;A++ ))
do
	for(( B=$COD;$B>1;B-- ))
	do
	echo -n " "
	done
	COD=$COD-1
	for(( C=1;$C<=($A\*2)-1;C++ ))
	do
	echo -n "*"
	done
echo
done


echo
echo "RAMID"
#TRIANGLE
COD=20
CO=20
for(( A=1;$A<=$CO;A++ ))
do
	for(( B=$COD;$B>1;B-- ))
	do
	echo -n "*"
	done
	COD=$COD-1
	for(( C=1;$C<=($A\*2)-1;C++ ))
	do
	echo -n " "
	done
	for(( B=$COD+1;$B>1;B-- ))
	do
	echo -n "*"
	done
echo
done

echo
echo "INVERSE PYRAMID"
#INVERSE TRIANGLE
COD=20
CO=20
for(( A=1;$A<=$CO;A++ ))
do
	for(( B=1;$B<$A;B++ ))
	do
	echo -n " "
	done
	for(( C=$COD;C>($A\*2)-($COD+1);C-- ))
	do
	echo -n "*"
	done
echo
done


echo
echo "DIAMOND"
#DIAMOND
COD=20
COD1=20
CO=20
for(( A=1;$A<=$CO;A++ ))
do
	for(( B=$COD;$B>1;B-- ))
	do
	echo -n " "
	done
	COD=$COD-1
	for(( C=1;$C<=($A\*2)-1;C++ ))
	do
	echo -n "*"
	done
echo
done
for(( A=1;$A<=$CO;A++ ))
do
	for(( B=0;$B<$A;B++ ))
	do
	echo -n " "
	done
	for(( C=$COD1;$C>($A\*2)-($COD1-1);C-- ))
	do
	echo -n "*"
	done
echo
done

echo
